name: Dotnet to ECS

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bug/**'
    paths:
      - 'Rt.Dotnet.EcsApi/**'
      - '.github/workflows/dotnet-ecs.actions.yml'

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          7.x
    - name: Run Unit Tests
      working-directory: Rt.Dotnet.EcsApi
      run: |
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: Rt.Dotnet.EcsApi
      run: docker build . --file Rt.Dotnet.EcsApi/Dockerfile --tag rt-dotnet-ecsapi:$(date +%s)
