name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          7.x
    - run: echo '${{ steps.stepid.outputs.dotnet-version }}'
    - name: Run Unit Tests
      run: |
        dotnet test
